# Generated by Django 5.2.4 on 2025-09-11 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('running', 'Running'), ('training', 'Training'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('tennis', 'Tennis'), ('golf', 'Golf'), ('outdoor', 'Outdoor'), ('fitness', 'Fitness'), ('yoga', 'Yoga'), ('skateboarding', 'Skateboarding'), ('surfing', 'Surfing'), ('hiking', 'Hiking'), ('climbing', 'Climbing'), ('water_sports', 'Water Sports'), ('winter_sports', 'Winter Sports'), ('other', 'Other')], default='other', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('product_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
